=== githof/buenosaires/Alpha/matrimonios.dtd
<!ELEMENT document (ACTES)>
<!ELEMENT ACTES (ACTE)+>
<!ELEMENT ACTE ( #PCDATA | date | epoux | epouse | parrains | temoins )*>
<!ATTLIST ACTE
	  num CDATA #IMPLIED
	  dispensa (true | false) "false"
>
<!ELEMENT date ( #PCDATA )* >
<!ELEMENT epoux ( #PCDATA | condition | prenom | nom | naissance-lieu | age | veuf-de | pere | mere )*>
<!ATTLIST epoux
	  id CDATA #IMPLIED
	  don (true | false) "false"
>
<!ELEMENT epouse ( #PCDATA | condition | prenom | nom | naissance-lieu | age | veuve | pere | mere )*>
<!ATTLIST epouse
	  id CDATA #IMPLIED
	  don (true | false) "false"
>
<!ELEMENT pere ( #PCDATA | condition | prenom | nom | veuf-de )*>
<!ATTLIST pere
	  id CDATA #IMPLIED
	  don (true | false) "false"
	  difunto (true | false) "false"
	  veuf (true | false) "false"
>
<!ELEMENT mere ( #PCDATA | condition | prenom | nom | veuve )*>
<!ATTLIST mere
	  id CDATA #IMPLIED
	  don (true | false) "false"
	  difunto (true | false) "false"
	  veuve (true | false) "false"
>
<!ELEMENT veuve ( #PCDATA | condition | prenom | nom )*>
<!ATTLIST veuve
	  id CDATA #IMPLIED
	  don (true | false) "false"
>
<!ELEMENT veuf-de ( #PCDATA | condition | prenom | nom )*>
<!ATTLIST veuf-de
	  id CDATA #IMPLIED
	  don (true | false) "false"
>
<!ELEMENT temoin ( #PCDATA | condition | prenom | nom )*>
<!ATTLIST temoin
	  id CDATA #IMPLIED
	  don (true | false) "false"
	  epouse (true | false) "false"
>
<!ELEMENT parrain ( #PCDATA | condition | prenom | nom )*>
<!ATTLIST parrain
	  id CDATA #IMPLIED
	  don (true | false) "false"
	  epouse (true | false) "false"
>
<!ELEMENT prenom ( #PCDATA )*>
<!ELEMENT nom ( #PCDATA )*>
<!ATTLIST nom
	  de (true | false) "false"
	  la (true | false) "false"
	  y (true | false) "false"
>
<!ELEMENT naissance-lieu ( #PCDATA )*>
<!ELEMENT age ( #PCDATA )*>
<!ELEMENT condition ( #PCDATA )*>
<!ELEMENT temoins ( #PCDATA | temoin )*>
<!ATTLIST temoins
	  conjoints (true | false) "false"
>
<!ELEMENT parrains ( #PCDATA | parrain )*>
<!ATTLIST parrains
	  conjoints (true | false) "false"
>

=== githof/buenosaires/old/Alpha/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "matrimonios.dtd">
<document>
  <ACTES>

    <ACTE num="5613">5643) <date>17-5-1777</date>: <epoux don="true">Dn.
    <prenom>Agustín</prenom> <prenom>Casimiro</prenom> de <nom
    de="true">AGUIRRE</nom>, natural de la Villa de <naissance-lieu>Donamaría,
    Obispado de Pamplona</naissance-lieu>, hijo legítimo de <pere don="true">
    Dn. <prenom>Francisco</prenom> <prenom>Casimiro</prenom> de <nom
    de="true">Aguirre</nom></pere> y de <mere don="true"> Da.
    <prenom>María</prenom> <prenom>Micaela</prenom> de <nom
    de="true">Micheo</nom> y <nom y="true">Ustariz</nom>,</mere></epoux> con
    <epouse don="true">Da. <prenom>María</prenom> <prenom>Josefa</prenom>
    <prenom>Engracia</prenom> <nom>ALONSO</nom> de la <nom de="true"
    la="true">JARROTA</nom> y (<nom y="true">ROZAS</nom>), natural de
    <naissance-lieu>ésta</naissance-lieu>, hija legítima de <pere don="true">
    Dn. <prenom>Domingo</prenom> <nom>Alonso</nom> de <nom
    de="true">Lajarrota</nom> y <nom y="true">Rozas</nom>,
    <condition>Caballero de la Orden de Alcántara</condition></pere> <mere
    don="true"> y de Da. <prenom>María</prenom> <prenom>Josefa</prenom> de la
    <nom de="true" la="true">Quintana</nom> y <nom y="true">Riglos</nom>.
    </mere></epouse>. Ts.: <temoins> los padres de la contrayente,
    </temoins>(f. 159).</ACTE>

    <ACTE num="5614">5644) <date>26-5-1777</date>: <epoux>José VIÑAS, natural
    de la ciudad de Mataró, Cataluña, hijo de <pere> Francisco Viñas</pere> y
    de <mere> María Viñas,</mere></epoux> con <epouse>Da. María Inés PEREYRA,
    natural de ésta, hija de <pere> Ricardo Pereyra</pere> y de <mere> María
    Josefa Cabral. </mere></epouse>. Ts.: <temoins><temoin> Dn. Nicolás
    Román</temoin> y <temoin>Da. Lorenza Pereyra. </temoin></temoins>(f.
    159).</ACTE>

    <ACTE num="6480">6519) <date>23-6-1804</date>: <epoux don="true">Dn.
    Gerardo BOSCH, natural de la ciudad de <naissance-lieu>Mataró, Obispado de
    Barcelona, Principado de Cataluña</naissance-lieu>, hijo legítimo de <pere
    don="true"> Dn. <prenom>Gerardo</prenom> <nom>Bosch</nom></pere> y de
    <mere don="true"> Da. <prenom>Isabel</prenom>
    <nom>Alvareda</nom>,</mere></epoux> con <epouse don="true">Da.
    <prenom>Juana</prenom> <prenom>Josefa</prenom> de <nom
    de="true">AGUIRRE</nom>, natural de <naissance-lieu>ésta</naissance-lieu>,
    hija legítima de <pere don="true"> Dn. <prenom>Cristóbal</prenom> de
    <nom>Aguirre</nom></pere> y de <mere don="true"> Da.
    <prenom>Manuela</prenom> <nom>López</nom> de <nom de="true">Anaya</nom>.
    </mere></epouse>. Ts.: <temoins><temoin don="true"> Dn.
    <prenom>Cristóbal</prenom> de <nom de="true">Aguirre</nom></temoin>,
    <temoin don="true" epouse="true">su esposa Da. <prenom>Manuela</prenom>
    <nom>López</nom> [de <nom de="true">Anaya</nom>]</temoin>, <temoin
    don="true">Dn. <prenom>Domingo</prenom> <nom>Miró</nom></temoin> y <temoin
    don="true">Dn. <prenom>Jaime</prenom> <nom>Batista</nom></temoin>,
    </temoins>(f. 435v.).</ACTE>

    <ACTE num="14008">14026) <date>1801</date>: <epoux>Bartolo ROBLE,</epoux>
    con <epouse>Josefa SANCHEZ,</epouse>. 175).</ACTE>

    <ACTE num="14009">14027) <date>1801</date>: <epoux>José LOPEZ,</epoux> con
    <epouse>Casimira CARAVAJAL.</epouse>. 175v).</ACTE>

    <ACTE num="14010">14028) <date>1801</date>: <epoux>Melcor
    VILLANUEVA,</epoux> con <epouse>Francisca SUAREZ.</epouse>. 176).</ACTE>

    <ACTE num="14011">14029) <date>1801</date>: <epoux>Pedro ACEVEDO,</epoux>
    con <epouse>Pascuala LERMA.</epouse>. 176v).</ACTE>

    <ACTE num="14012">14030) <date>1801</date>: <epoux>Juan Antonio
    MARQUEZ,</epoux> con <epouse>Josefa MURAÑA.</epouse>. 176).</ACTE>

    <ACTE num="14013">14031) <date>1801</date>: <epoux>José Antonio de la
    ROSA,</epoux> con <epouse>Juana BAEZ.</epouse>. 177).</ACTE>

    <ACTE num="14014">14032) <date>1801</date>: <epoux>José M. de
    LEON,</epoux> con <epouse>Antonia PAZ.</epouse>. 177v).</ACTE>
  </ACTES>
</document>

=== githof/buenosaires/old/Alpha/buenosaires-base.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "matrimonios.dtd">
<document><ACTES>
<ACTE num="5"> 1)<date>4-2-1656</date> :     <epoux id="1"><condition>Capitán</condition> <prenom>Juan</prenom>     <nom>ZACARIAS</nom> de la <nom de="true" la="true">SIERRA</nom> y     <nom>MORALES</nom> </epoux>, con <epouse don="true" id="2">Da.     <prenom>María</prenom> de <nom de="true">CARAVAJAL</nom>, <veuve id="3">viuda del     <condition>Capitán</condition> <prenom>Cristóbal</prenom>     <nom>Cabral</nom> </veuve> </epouse>.<temoins>Ts.:     el<temoin id="4"><condition>Capitán</condition><prenom>Diego</prenom><nom>Gutiérrez</nom>de     <nom de="true">Humanes</nom></temoin><temoin id="5"><prenom>Juan</prenom>de<nom>Ibarra     o Izarra</nom></temoin>,<temoin id="6">el<condition>Alférez</condition>     <prenom>Juan</prenom> <nom>Rodríguez</nom> <nom>Estela</nom> </temoin>, y     otros muchos</temoins>, (f. 1).</ACTE>
<ACTE num="8193"> 8233) <date>22-9-1755</date> :     <epoux id="7"><prenom>Juan Esteban</prenom>de <nom de="true">OLEA</nom>,     <condition>indio</condition>, <naissance-lieu>natural de     Tucumán</naissance-lieu>, hijo legítimo de <pere id="9">     <prenom>Agustín</prenom> de <nom de="true">Olea</nom> </pere> y de <mere id="10">         <prenom>Cristina</prenom>       </mere>, indios</epoux>, con <epouse id="8"><prenom>María Pascuala</prenom>     <nom>ORTIZ</nom>, española, <naissance-lieu>natural de     ésta</naissance-lieu>, hija legítima de <pere id="11">         <prenom>Pedro</prenom>          <nom>Ortiz</nom>       </pere>, difunto, y de <mere id="12">         <prenom>Juana Gregoria</prenom>          <nom>Ramírez</nom>       </mere></epouse>. <temoins>Ts.: <temoin id="13">         <prenom>Francisco</prenom>          <nom>Guzmán</nom>       </temoin>, y <temoin id="14">         <prenom>Sabina</prenom>          <nom>Alvarado</nom>       </temoin></temoins>. Nota: C 8/214, "Juan Esteban Olea, mestizo al     parecer, y María Pascuala Ortiz, que se duda si es española, pero ella     dice que sí, y pobre", (f. 130).</ACTE>
<ACTE num="7232">7277) <date>14-5-1815</date>: <epoux id="414">Señor     <condition>Coronel Mayor </condition>Dn. <prenom>Juan     </prenom><prenom>Martín</prenom> de <nom de="true">PUEYRREDON</nom>,     natural de <naissance-lieu>ésta</naissance-lieu>, hijo legítimo de     <pere id="526">Dn. <prenom>Juan</prenom> <nom>Martín</nom> de <nom de="true">Pueyrredón</nom></pere> y de Da. <mere id="415">         <prenom>Rita </prenom>          <nom>Dogan</nom>       </mere></epoux>, con <epouse id="525">Da. <prenom>María     </prenom><prenom>Calixta</prenom> <nom>TELLECHEA</nom>, natural de     <naissance-lieu>ésta</naissance-lieu>, hija legítima de <pere don="true" id="384">Dn. <prenom>Francisco </prenom><nom>Tellechea</nom> </pere>y de     Da. <mere don="true" id="385">         <prenom>Matea </prenom>          <nom>Caviedes</nom>       </mere></epouse>. Ts.:<temoins conjoints="true"> <temoin don="true" id="527">Dn.     <prenom>Manuel </prenom><nom>Martínez</nom> <nom>García</nom> </temoin>y     su esposa <temoin don="true" epouse="true" id="386">Da. <prenom>Damasia     </prenom><nom>Caviedes</nom></temoin></temoins>. (f. 141v.).</ACTE>
<ACTE num="4097">4108)<date>8-12-1750</date>: <epoux id="15">Dn. <prenom>Francisco     Antonio</prenom> de <nom de="true">CONGET</nom></epoux>, con <epouse id="16">Da.     <prenom>Antonia Margarita</prenom> <nom>de     RAMOS</nom><naissance-lieu>naturales de ésta</naissance-lieu>,</epouse> .     Ts.: (<temoins> <temoin id="17"> Dn. <prenom>Mateo</prenom> <nom>de     Ramos</nom></temoin> y <temoin id="18">Da. <prenom>Margarita</prenom>     <nom>Monzón</nom> <nom>Díaz</nom> </temoin></temoins>), (f. 23).</ACTE>

</ACTES></document>
